### ISSUE TITLE
Isn't log enabled by default

### ISSUE THREAD

**Issue by YusufIpek** [jernejk/JSNLog#4]
https://github.com/jernejk/JSNLog/blob/19811ab7aba9b5cc442bdd693cd3b7cfa05b8efa/JSNLog.Web/src/app/app.component.ts#L13

I have a question about the comment, you are saying that "By default the log is disabled which means it's not necessary to call init with `isLogEnabled = false`". What do you mean by that? Isn't the log enabled by default? Because isLogEnabled has the default value true.

**Comment by jernejk** [comment]
Ah, sorry about the odd comment.

If `init()` is not called, `isLogEnabled` remains `false`.
That means that if you don't need logging, you can just comment out/remove `init()`.

Alternatively, you can also call `init()` like this:

``` js
log.init('http://localhost:51213/jsnlog.logger', 'ALL', false);
```

And that would disable logging as well.

This can be useful if you want to dynamically enable logging on demand for example if you want to enable a diagnostic feature.
If the app is used in an environment where sending diagnostic data isn't allowed unless the user approves, this can be a great way to implement this feature. 😊

You just need to add a method in *log.service.ts* that sets `isLogEnabled = true;`.
